import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { promises as fs } from "node:fs";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { q } from "@/lib/db";
import { accountFor, AUTH_COOKIE } from "@/lib/auth";
import { repoRoot, runPython } from "@/lib/pyRun";

/**
 * GET /api/candidates/[id]/dossier — stream the RUH-branded candidate dossier PDF (Track 3), generated by
 * agent/candidate_dossier_pdf.py (WeasyPrint) from the stored screening + prep + interview. HR-only
 * (candidate PII). Advisory — the dossier is a review aid; a human decides.
 */
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function slug(s: string): string {
  return (s || "candidate").toLowerCase().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-").slice(0, 60) || "candidate";
}

export async function GET(_req: Request, ctx: { params: Promise<{ id: string }> }) {
  const acct = accountFor((await cookies()).get(AUTH_COOKIE)?.value);
  if (!acct) return NextResponse.json({ ok: false, error: "not signed in" }, { status: 401 });
  if (acct.role !== "hr") return NextResponse.json({ ok: false, error: "HR only" }, { status: 403 });

  const { id } = await ctx.params;
  let cand: { name: string } | undefined;
  try {
    cand = (await q<{ name: string }>("SELECT name FROM candidates WHERE id = $1::uuid", [id]))[0];
  } catch { return NextResponse.json({ ok: false, error: "invalid candidate id" }, { status: 400 }); }
  if (!cand) return NextResponse.json({ ok: false, error: "candidate not found" }, { status: 404 });

  const root = repoRoot();
  if (!root) return NextResponse.json({ ok: false, error: "dossier generator not found on server" }, { status: 500 });

  const pdfPath = path.join(os.tmpdir(), `dossier-${randomUUID()}.pdf`);
  const script = path.join(root, "agent", "candidate_dossier_pdf.py");
  try {
    const { code, stderr } = await runPython([script, "--candidate", id, "--output", pdfPath], root);
    if (code !== 0 || !existsSync(pdfPath)) {
      return NextResponse.json({ ok: false, error: `dossier generation failed: ${stderr.slice(0, 300)}` }, { status: 502 });
    }
    const buf = await fs.readFile(pdfPath);
    return new NextResponse(new Uint8Array(buf), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="dossier-${slug(cand.name)}.pdf"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (e) {
    return NextResponse.json({ ok: false, error: (e as Error).message }, { status: 500 });
  } finally {
    fs.unlink(pdfPath).catch(() => {});
  }
}
